# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=8, unique=True)),
                ('upc', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manufacturer', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.Category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.Item')),
            ],
            options={
                'verbose_name_plural': 'Item categories',
                'db_table': 'item_categories',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WholesaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('acqusition_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale', to='inventory.Item')),
            ],
            options={
                'ordering': ['acqusition_date'],
                'db_table': 'wholesale_items',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together=set([('item', 'category')]),
        ),
    ]
